version: "3.8"
services:

  backend:
    restart: always
    build:
      dockerfile: dockerFiles/backend.Dockerfile
      context: .
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - APP_PORT=8000

  frontend:
    restart: always
    build:
      dockerfile: dockerFiles/frontend.Dockerfile
      context: .
    ports:
      - 80:80
      - 443:443
    environment:
      - ENV_CONFIGURATION=production
