version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # Update packages.
      - apt-get update -y -q

      # Install @angular/cli and app dependencies.
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g sonarqube-scanner
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

  build:
    commands:
      # Run code quality tools.
      - echo Running code quality checks...
      - npm run lint

      # Sonar cloud checks
      - echo Running Sonar cloud checks...
      - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.organization=$SONAR_ORGANIZATION
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECT >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi

      - docker build . -t $REPOSITORY_URI:latest -f dockerFiles/backend.Dockerfile

cache:
  paths:
    - '/**/*'
